export const ROUTES = {
  MAIN_TABS: 'MainTabs',
  HOME: 'Home',
  SUBJECTS: 'Subjects',
  SUBJECT_DETAIL: 'SubjectDetail',
  FOLDER_DETAIL: 'FolderDetail',
  CREATE_SUBJECT: 'CreateSubject',
  CREATE_FOLDER: 'CreateFolder',
  SCANNER: 'Scanner',
  SCAN_PREVIEW: 'ScanPreview',
  SAVE_NOTE: 'SaveNote',
  NOTE_VIEWER: 'NoteViewer',
  CREATE_PDF: 'CreatePdf',
  PDF_VIEWER: 'PdfViewer',
  SEARCH: 'Search',
  FAVORITES: 'Favorites',
  TRASH: 'Trash',
  SETTINGS: 'Settings',
} as const;
